#pragma once

#include "Functions.h"
#include "Caches.h"

#define STREAM_NONAME "<noname>"
#define STREAM_NONAME_W L"<noname>"


// FixupUSA1 - corrupted data
// MFT record is not in use
// incorrect parameters in function call
// incorrect data in data runs bytes
// LoadMFTRecordCache returned nullptr
// ReadClusters failed
// LoadMFTRecord failed
// DeviceIoControl failed
// DeviceIoControl returned another MFT record than requested
// 
enum class TError 
{    
	Success,    
	MFTRecordNotInUse,
	InvalidArgument,   
	CorruptedData, // mostly generated by FixupUSA and DecodeDataRuns
	IOError, // generated mostly by ReadClusters, LoadMFTRecord and DeviceIoControl
};

class IRecordLoader
{
protected:
	VOLUME_DATA FVolumeData;
	TMFTRecCache FMFTRecCache; // = Singleton<TMFTRecCache>::getInstance();

public:
	static string_t ParseVolume(const string_t& vol);
	const VOLUME_DATA& GetVolumeData() const { return FVolumeData; }
	virtual void OpenVolume(const string_t& vol) = 0;
	virtual bool LoadMFTRecord(MFT_REF mftRecRef, uint8_t* mftRecData) = 0;
	virtual bool ReadClusters(CLST lcnStart, CLST lcnCnt, uint8_t* dataBuf) = 0;

	// FixupUSA1 makes USA fixes in buffer refered by record param.
	// This function is going to be used for processing ALLOC attr Index Blocks or MFT records (only when they read directly from disk, not via WINAPI). 
	// When MFT records loadded via WINAPI call they already have USA fixed up.
    // BytesPerBlock value is usually defined in ATTR_ROOT attr (field IndexBlockSize) and it may differ from filesystem's ClusterSize.
	// For MFT records BytesPerBlock is standard MFT record size (BytesPerMFTRec)
    // record buffer should be at least BytesPerBlock size
	static bool FixupUSA1(NTFS_RECORD_HEADER* record, uint32_t BytesPerBlock, uint32_t BytesPerSector)
	{
		UNREFERENCED_PARAMETER(BytesPerBlock);

		uint32_t wordsPerSector = BytesPerSector >> 1;

		uint16_t sectorsCnt = record->FixupCnt - 1;
		assert(sectorsCnt == BytesPerBlock / BytesPerSector);

		uint16_t* fixupArr = (uint16_t*)(Add2Ptr(record, record->FixupOffset));
		uint16_t checkValue = *fixupArr;
		fixupArr++; // now it refers to first array item

		uint16_t* sectorEnd = (uint16_t*)(record) + wordsPerSector - 1;

		uint32_t s = 0;
		while (s < sectorsCnt)
		{
			assert(checkValue == *sectorEnd);
			if (checkValue != *sectorEnd)
			{
				GET_LOGGER;
				logger.Error("[FixupUSA1] Error: looks like data is corrupted in the sector");
				return false; // looks like data is corrupted in this sector
			}

			*sectorEnd = fixupArr[s]; // restore data

			sectorEnd += wordsPerSector;
			s++;
		}

		return true;
	}

	// FixupUSA is used for processing ALLOC Data Runs only. All other MFT records are loadded via WINAPI call already have fixed up USA.
	// That is why FixupUSA has to work with indexBlockSize that differs from ClusterSize.
	// This is main goal of indexBlockSize parameter - support non-standard Index Blocks size that differ from ClusterSize. 
	// iblocksCount - number of Index Blocks that dataBuf buffer contains (each block is indexBlockSize size)
	// startCLN - needed only for warning message about missing 'INDX' to identify which LCN is missing this signature
	// dataBuf must contain data at least for iblocksCount Index Blocks of indexBlockSize size each.
	/*virtual bool FixupUsaINDX(uint8_t* dataBuf, CLST startLCN, uint64_t iblocksCount, uint32_t indexBlockSize)
	{
		NTFS_RECORD_HEADER* indexRec = (NTFS_RECORD_HEADER*)dataBuf;
		uint32_t k = indexBlockSize / FVolumeData.BytesPerCluster;

		// loop by LCNs loaded into dataBuf
		for (uint64_t i = 0; i < iblocksCount; i++)
		{
			if (!ntfs_is_indx_recp(indexRec->Signature)) // bypass non 'INDX' clusters (usually filled by zero)
			{
				/* This is correct situation when list of LCNs in one data run has "holes" according to Bitmap attribute.
				*  We read all LCNs from current data run as a single operation. Some of these LCNs are "not used" and do not contain INDX signature
				*  Such LCNs have appropriate bit=0 in Bitmap attribute.
				*/
	/*
				GET_LOGGER;
				uint8_t* sign = indexRec->Signature;
				logger.WarnFmt("[FixupUsaINDX] Signature 'INDX' has not been found in LCN cluster {}. Signature found: {}{}{}{}", startLCN + i * k, sign[0], sign[1], sign[2], sign[3]);

				continue;
			}

			if (!FixupUSA1(indexRec, indexBlockSize, FVolumeData.BytesPerSector))
			{
				GET_LOGGER;
				logger.Error("[FixupUsaINDX] FixupUSA1 returned error!");
				return false;
			}

			/*uint16_t sectorsCnt = indexRec->FixupCnt - 1;
			assert(sectorsCnt == /*getVolData().BytesPerCluster*/ /*indexBlockSize / getVolData().BytesPerSector);

			uint16_t* fixupArr = (uint16_t*)(Add2Ptr(indexRec, indexRec->FixupOffset));
			uint16_t checkValue = *fixupArr;
			fixupArr++; // now it refers to first array item

			uint16_t* sectorEnd = (uint16_t*)(indexRec)+wordsPerSector - 1;

			uint32_t s = 0;
			while (s < sectorsCnt)
			{
				assert(checkValue == *sectorEnd);
				if (checkValue != *sectorEnd)
				{
					GET_LOGGER;
					logger.Error("[FixupUSA] Error: looks like data is corrupted in the sector");
					return false; // looks like data is corrupted in this sector
				}

				*sectorEnd = fixupArr[s]; // restore data

				sectorEnd += wordsPerSector;
				s++;
			}*/
/*
			indexRec = (NTFS_RECORD_HEADER*)Add2Ptr(indexRec, indexBlockSize);
		}

		return true;
	}
	*/

	virtual uint8_t* LoadMFTRecordCache(MFT_REF mftRecRef) // returns NULL if error occurred during loading MFT record
	{
		uint8_t** result = FMFTRecCache.GetValuePointer(mftRecRef.sId.low);
		if (result == nullptr) // no value in cache, load MFT record from disk
		{
			uint8_t* mftRecBuf = DBG_NEW uint8_t[FVolumeData.BytesPerMFTRec];
			if (!LoadMFTRecord(mftRecRef, mftRecBuf))
				return nullptr; // error loading MFT record

			//we use mftRecRef.sId.low here because high part of mftRecRef.Id may change when MFT record is modified
			FMFTRecCache.SetValue(mftRecRef.sId.low, mftRecBuf); // update cache

			return mftRecBuf;
		}

		return *result; // return MFT record from cache
	}

	virtual void CloseVolume()
	{
		// closes volume handle opened by OpenVolume
		// clears data about volume, clears caches

		GET_LOGGER;
		logger.DebugFmt("Closing volume: {}", wtos(FVolumeData.Name));

		CloseHandle(FVolumeData.hVolume);
		auto& volDataBuf = (NTFS_VOLUME_DATA_BUFFER&)FVolumeData;
		ZeroMemory(&volDataBuf, sizeof(NTFS_VOLUME_DATA_BUFFER));
		FVolumeData.hVolume = INVALID_HANDLE_VALUE;
		FVolumeData.Name.clear();
		FMFTRecCache.Clear();
	}
};

class TMFTRecordLoader : public IRecordLoader
{
public:
	TMFTRecordLoader() { }
	TMFTRecordLoader(const string_t& vol) { OpenVolume(vol); }
	void OpenVolume(const string_t& vol) override;
	bool ReadClusters(CLST lcnStart, CLST lcnCnt, uint8_t* dataBuf) override;
	bool LoadMFTRecord(MFT_REF mftRecRef, uint8_t* mftRecData) override;
};


class TMFTParserBase
{
protected:
	IRecordLoader& FLoader;
	const VOLUME_DATA& getVolData() const { return FLoader.GetVolumeData(); }
public:
	TMFTParserBase(IRecordLoader& loader) : FLoader(loader) {};

	//bool FixupUSA(uint8_t* dataBuf, CLST startLCN, uint64_t iblocksCount, uint32_t indexBlockSize);
	//void FillAttrValues(MFT_FILE_RECORD* mftRec, PMFT_ATTR_HEADER* attrValues);
	bool FillAttrCollection(MFT_FILE_RECORD* mftRec, TAttrCollection& collection);
	bool FillAttrCollection(MFT_FILE_RECORD* mftRec, uint32_t attrFilter, TAttrCollection& collection);
	//bool FillCollectionFromAttrList(MFTRecIndex indexMFTRec, uint32_t attrFilter, ATTR_LIST_ENTRY* startListItem, uint8_t* attrListEnd1, uint8_t* attrListEnd2, TAttrCollection& collection);

	//void GetAttr(ATTR_TYPE attrType, const PMFT_ATTR_HEADER* const attrValues, PMFT_ATTR_HEADER* result);
	void GetFileListFromNode(INDEX_HDR* ihdr, TLCNRecs& lcns, TFileList& fnames);
	void GetFileList(INDEX_HDR* ihdr, AddFileAttrPred pred);

	//bool ReadClusters(CLST lcnStart, CLST lcnCnt, uint8_t* dataBuf);
	bool ParseNonresAttrList(MFTRecIndex indexMFTRec, MFT_ATTR_HEADER* attrListAttr, AttrListPred processChildMFTRecPred);
	bool ParseNonresAttrList(MFTRecIndex indexMFTRec, uint32_t attrFilter, MFT_ATTR_HEADER* attrListAttr, AttrListPred processChildMFTRecPred);
	//bool GetAttrFromAttrList(ATTR_LIST_ENTRY* startListItem, ATTR_TYPE attrType, uint8_t* attrListEnd1, uint8_t* attrListEnd2, PMFT_ATTR_HEADER* result);
	bool ParseNonresBitmap(MFT_ATTR_HEADER* attr, TBitField& bitmap);
	bool ParseBitmap(MFT_ATTR_HEADER* attr, TBitField& bitmap);
	void ParseIndexRoot(MFT_ATTR_HEADER* attr, TLCNRecs& lcns, TFileList& fileList);
	//bool ParseAlloc(MFT_ATTR_HEADER* attr, TDataRuns& dataRuns);
	void ParseAttrList(MFTRecIndex indexMFTRec, uint32_t attrFilter, ATTR_LIST_ENTRY* startListItem, uint8_t* attrListEnd, uint64_t realSize, uint64_t& processedAttrSize, AttrListPred processChildMFTRecPred);
	void ParseAttrList(MFTRecIndex indexMFTRec, ATTR_LIST_ENTRY* startListItem, uint8_t* attrListEnd, uint64_t realSize, uint64_t& processedAttrSize, AttrListPred processChildMFTRecPred);
	bool ProcessAllocDataRuns(DIR_NODE& node, ProcessiBlocksPred processIndexBlockPred);
	bool DecodeDataRuns(MFT_ATTR_HEADER* attr, TDataRuns& runs);
	
	ATTR_FILE_NAME* GetFileNameAttr(MFT_FILE_RECORD* mftRec);
	std::wstring GetPathByAttrFileName(ATTR_FILE_NAME* attrFileName);
	void GetFileNameAttrPointers(MFT_FILE_RECORD* mftRec, THArray<ATTR_FILE_NAME*>& attrFileNames);
	
	int32_t GetFileListFromMFTRec(MFT_FILE_RECORD* mftRec, DIR_NODE& node);
	bool GetPathByMFTRecID(MFT_REF mftRecRef, THArray<std::wstring>& paths);
    MFTRecIndex GetMFTRecIdByPath(const ci_string& path); // ci_string is for case INsensitive search here
};

class TMFTStatCollector : public TMFTParserBase
{
private:
	TItemInfoList FItemsList;
	bool FProcessNonResAttr; // whether to process non-resident attrs. for some tests it is not needed to process non-res attrs
public:
	TMFTStatCollector(IRecordLoader& loader, bool processNonRes = true) : TMFTParserBase(loader), FProcessNonResAttr(processNonRes) {};
	
	bool ReadMftItems(MFT_REF startMftRecRef, uint32_t dirLevel);
	bool ReadMftItemInfo(MFT_REF mftRecRef, ITEM_INFO& itemInfo);
	bool ReadMftItemInfoBuf(MFT_FILE_RECORD* mftRec, ITEM_INFO& itemInfo);
	void ShowVolumeStat();

};

class TMFTSearchReader: public TMFTParserBase
{
public:
	TFileCache FFileList;

	TMFTSearchReader(IRecordLoader& loader) : TMFTParserBase(loader) { }
	bool ParseMFTRecord(uint8_t* mftRecData, DIR_NODE& node, uint32_t parentIdx, TFileCache::TLevel* level);

	bool ReadDirectoryV1(uint32_t parentIdx, CACHE_ITEM* parentItem, uint64_t& dirSize, ProgressCallbackPtr callback);
	void ReadDirsV1();
};

class TMFTSearchReaderV2 : public TMFTParserBase
{
private:
	TFileList FDirList;
public:
	TMFTSearchReaderV2(IRecordLoader& loader) : TMFTParserBase(loader) { } 

	bool ReadDirectoryV2(MFT_REF parentMftRecID, uint32_t dirLevel);
	void ReadDirsV2();
};
